version: "3.3"

services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:30188"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
